on:
  push:
  pull_request:

jobs:
  cmake_build:
    name: "CMake build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Install Dependencies"
        run: |
          mkdir /tmp/catch2
          curl -L https://github.com/catchorg/Catch2/archive/refs/tags/v3.0.1.tar.gz | tar xz -C /tmp/catch2 --strip-components=1
          cmake -S /tmp/catch2 /tmp/build_catch -DCMAKE_INSTALL_PREFIX=~/.local/
          cmake --build /tmp/build_catch -- -j 2
          cmake --install /tmp/build_catch

      - name: "Build"
        run: |
          cmake --version
          cmake -S . -B build \
            -DCMAKE_CXX_FLAGS="-Werror -Wextra -Wall -Wpedantic -Wconversion -Wsign-compare -Wunreachable-code -Wunused" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=~/.local/fibonacci \
            -DBUILD_SHARED_LIBS=ON
          cmake --build build -- -j 2
          cmake --install build

      - name: "Run"
        run: |
          ~/.local/fibonacci/bin/fibonacci -v
          ~/.local/fibonacci/bin/fibonacci -h
          ~/.local/fibonacci/bin/fibonacci 10

      - name: "Tests"
        run: |
          ./build/tests/tests --colour-mode ansi
